# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  text-editor-challenge-benchmarks:
    dependencies:
    - base
    - text-editor-challenge
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: text-editor-challenge is one solution for the simple-text-editor kata.
executables:
  text-editor-challenge:
    dependencies:
    - base
    - text-editor-challenge
    - trifecta
    - bytestring
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options:
  - -Wall
  - -O2
github: githubuser/text-editor-challenge
library:
  dependencies:
  - base
  - text
  - containers
  - safe
  - bytestring
  - trifecta
  - parsers
  source-dirs: library
maintainer: Jesse Hanley
name: text-editor-challenge
synopsis: Solution for text editor kata
tests:
  text-editor-challenge-test-suite:
    dependencies:
    - base
    - text-editor-challenge
    - tasty
    - tasty-hspec
    - containers
    - bytestring
    - trifecta
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.0'
