# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  simple-text-editor-benchmarks:
    dependencies:
    - base
    - simple-text-editor
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: simple-text-editor is a new Haskeleton package.
executables:
  simple-text-editor:
    dependencies:
    - base
    - simple-text-editor
    - mtl
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/simple-text-editor
library:
  dependencies:
  - base
  - text
  - containers
  - safe
  - bytestring
  - trifecta
  - parsers
  source-dirs: library
maintainer: Jesse Hanley
name: simple-text-editor
synopsis: A new Haskeleton package.
tests:
  simple-text-editor-test-suite:
    dependencies:
    - base
    - simple-text-editor
    - tasty
    - tasty-hspec
    - containers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
